# Generated by Django 5.0.6 on 2024-05-23 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_producto_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='custom_id',
        ),
    ]
