# Generated by Django 5.0.6 on 2024-05-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_002_CarritoCompras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
